# Настройки физической монеты
coin-settings:
  # Материал предмета (должен быть строго как в Spigot API, капсом)
  # Список материалов: https://papermc.io
  material: "GOLD_NUGGET"

  # Название предмета в игре (поддерживает цветовые коды &)
  display-name: "&6Монета"

  # Сообщения плагина
  messages:
    success: "&aВыдана одна монета."
    inventory-full: "&eВаш инвентарь был полон! Монета сброшена под ноги."
