name: MoneyPlugin
version: 0.6
main: ru.kpanicshop.moneyPlugin.MoneyPlugin
api-version: '1.21.4'

commands:
  money:
    description: Выдать защищенную физическую монету
  trade:
    description: Открыть встроенное GUI-меню обмена предметами между игроками
